spring:
  application:
    name: brokerage-firm
  datasource:
    url: jdbc:h2:mem:brokerage
    username: admin
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      path: /h2-console
      enabled: true

server:
  port: 8080


