-- =========================
-- SCHEMA INITIALIZATION
-- =========================

CREATE TABLE customers (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           username VARCHAR(64) UNIQUE NOT NULL,
                           password VARCHAR(100) NOT NULL,
                           roles VARCHAR(64) NOT NULL,
                           created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE assets (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        customer_id BIGINT NOT NULL,
                        asset_name VARCHAR(32) NOT NULL,
                        size DECIMAL(19,4) NOT NULL,
                        usable_size DECIMAL(19,4) NOT NULL,
                        version BIGINT NOT NULL DEFAULT 0,
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT uk_cust_asset UNIQUE (customer_id, asset_name),
                        CONSTRAINT fk_asset_customer FOREIGN KEY (customer_id) REFERENCES customers(id)
);

CREATE TABLE orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        customer_id BIGINT NOT NULL,
                        asset_name VARCHAR(32) NOT NULL,
                        order_side VARCHAR(8) NOT NULL,
                        size DECIMAL(19,4) NOT NULL,
                        price DECIMAL(19,4) NOT NULL,
                        status VARCHAR(16) NOT NULL,
                        create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        idempotency_key VARCHAR(64),
                        version BIGINT NOT NULL DEFAULT 0,
                        CONSTRAINT fk_order_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
                        CONSTRAINT uk_idem UNIQUE (idempotency_key)
);

-- =========================
-- INITIAL USERS (bcrypt hashes)
-- admin / alice / bob
-- =========================
INSERT INTO customers(username, password, roles) VALUES
                                                     ('admin', '$2a$10$UWegJWLhz1TzHwPgxc6h8upvX9Zi42pqR6mqKa92u5TrBjzQSd1ke', 'ROLE_ADMIN'), -- BCrypt'e dönerken burayı değiştireceksiniz.
                                                     ('alice', '{noop}alice123', 'ROLE_CUSTOMER'),
                                                     ('bob',   '{noop}bob123', 'ROLE_CUSTOMER');


INSERT INTO assets(customer_id, asset_name, size, usable_size) VALUES
                                                                   ((SELECT id FROM customers WHERE username='alice'), 'TRY', 100000.0000, 100000.0000),
                                                                   ((SELECT id FROM customers WHERE username='bob'), 'TRY', 50000.0000, 50000.0000);
